# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activesupport/all/activesupport.rbi
#
# activesupport-8.0.1

module ActiveSupport
end
module ActiveSupport::TaggedLogging
  def clear_tags!(*, **, &); end
  def flush; end
  def pop_tags(*, **, &); end
  def push_tags(*, **, &); end
  def self.logger(*args, **kwargs); end
  def self.new(logger); end
  def tagged(*tags); end
end
module ActiveSupport::TaggedLogging::Formatter
  def call(severity, timestamp, progname, msg); end
  def clear_tags!; end
  def current_tags; end
  def pop_tags(count = nil); end
  def push_tags(*tags); end
  def tag_stack; end
  def tagged(*tags); end
  def tags_text; end
end
class ActiveSupport::TaggedLogging::TagStack
  def clear; end
  def format_message(message); end
  def initialize; end
  def pop_tags(count); end
  def push_tags(tags); end
  def tags; end
end
module ActiveSupport::TaggedLogging::LocalTagStorage
  def self.extended(base); end
  def tag_stack; end
  def tag_stack=(arg0); end
end
