# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/i18n/all/i18n.rbi
#
# i18n-1.14.6

module I18n
end
module I18n::Locale
end
module I18n::Locale::Tag
end
class I18n::Locale::Tag::Simple
  def initialize(*tag); end
  def self.tag(tag); end
  def subtags; end
  def tag; end
  def to_a; end
  def to_s; end
  def to_sym; end
  include I18n::Locale::Tag::Parents
end
