# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/logger/all/logger.rbi
#
# logger-1.6.4

class Logger
  def <<(msg); end
  def add(severity, message = nil, progname = nil); end
  def close; end
  def datetime_format; end
  def datetime_format=(datetime_format); end
  def debug!; end
  def debug(progname = nil, &block); end
  def debug?; end
  def error!; end
  def error(progname = nil, &block); end
  def error?; end
  def fatal!; end
  def fatal(progname = nil, &block); end
  def fatal?; end
  def format_message(severity, datetime, progname, msg); end
  def format_severity(severity); end
  def formatter; end
  def formatter=(arg0); end
  def info!; end
  def info(progname = nil, &block); end
  def info?; end
  def initialize(logdev, shift_age = nil, shift_size = nil, level: nil, progname: nil, formatter: nil, datetime_format: nil, binmode: nil, shift_period_suffix: nil, reraise_write_errors: nil); end
  def level; end
  def level=(severity); end
  def level_key; end
  def level_override; end
  def log(severity, message = nil, progname = nil); end
  def progname; end
  def progname=(arg0); end
  def reopen(logdev = nil); end
  def sev_threshold; end
  def sev_threshold=(severity); end
  def unknown(progname = nil, &block); end
  def warn!; end
  def warn(progname = nil, &block); end
  def warn?; end
  def with_level(severity); end
  include Logger::Severity
end
