# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rbs/all/rbs.rbi
#
# rbs-3.8.0

module RBS
  def self.logger; end
  def self.logger_level; end
  def self.logger_level=(level); end
  def self.logger_output; end
  def self.logger_output=(val); end
  def self.print_warning; end
end
