# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/terminal-table/all/terminal-table.rbi
#
# terminal-table-3.0.2

module Terminal
end
class Terminal::Table
end
