# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/typeprof/all/typeprof.rbi
#
# typeprof-0.30.1

module TypeProf::CLI
end
class TypeProf::CLI::CLI
  def cli_options; end
  def core_options; end
  def find_files; end
  def initialize(argv); end
  def lsp_options; end
  def run; end
  def run_cli(core); end
  def run_lsp(core); end
  def set_profiler; end
  def setup_rbs_collection(path); end
end
